config/routes.rb
Rails.application.routes.draw do
  
  root "posts#index"
  
  devise_for :users
  resources :users
  
  resources :friendships
  
  resources :searches
  
  
  resources :posts do
    resources :comments
    member {post :vote}
  end 
  
  resources :comments do
    resources :comments
  end
  

  

end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :commentable, polymorphic: true
  has_many :comments, as: :commentable
  belongs_to :post
  has_one :user
end

app/models/friendship.rb
class Friendship < ActiveRecord::Base
    belongs_to :user
    belongs_to :friend, :class_name => "User"
end

app/models/post.rb
class Post < ActiveRecord::Base
    belongs_to :user
    has_many :comments, as: :commentable
    has_reputation :votes, source: :user, aggregated_by: :sum

    def self.search(search)
        if search
            where(["title LIKE ? OR body LIKE ?","%#{search}%","%#{search}%"])
        else 
            all 
        end 
    end 
end

app/models/search.rb
class Search < ActiveRecord::Base
    
    def search_posts
        
        posts = Post.all
        
        posts = posts.where(["category LIKE ?", category]) if category.present?
        
        return posts
        
    end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
         
  has_many :posts
  has_many :comments, through: :posts
  
  has_many :friendships
  has_many :friends, :through => :friendships
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user  
  
  #For Paperclip
  
  has_attached_file :image, styles: { medium: "300x300>", thumb: "100x100>" }, default_url: "/app/assets/images/placehold.gif"
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\z/

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
    before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:Username, :email, :Location, :Profession, :Education, :Biography, :password, :image])
    devise_parameter_sanitizer.permit(:sign_in, keys: [:email, :password, :remember_me])
    devise_parameter_sanitizer.permit(:account_update, keys: [:Username, :email, :Location, :Profession, :Education, :Biography, :password, :image])
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
    before_action :find_commentable


    def new
      @comment = Comment.new
    end
    
    def edit
    @comment = @commentable.comments.find(params[:id])
    end

    def create
      if user_signed_in?
      @comment = @commentable.comments.new comment_params
      @comment.user_id=current_user.id if current_user
      @comment.Username = current_user.Username if current_user
          @comment.save
        redirect_to :back, notice: 'Your comment was successfully posted!'
      else
        redirect_to '/users/sign_in', notice: "Your comment wasn't posted! Please sign in!"
      end
    end
    
   def update
     @comment = Comment.find(params[:id])
      if @comment.update_attributes(comment_params)
        redirect_to @comment.commentable, notice: "Comment was updated."
      else
        render :edit, notice: 'Your comment was not updated!'
      end
   end
    
    def destroy
      @comment = Comment.find(params[:id])
      @comment.destroy
    
      redirect_to :back
    end

    private

    def comment_params
      params.require(:comment).permit(:body)
    end

    def find_commentable
      @commentable = Comment.find_by_id(params[:comment_id]) if params[:comment_id]
      @commentable = Post.find_by_id(params[:post_id]) if params[:post_id]
    end

end

app/controllers/friendships_controller.rb
class FriendshipsController < ApplicationController

    def create
      if current_user.friendships.where(friend_id: params[:friend_id]).present?
        flash[:notice] = "Friendly already exist!"
        redirect_to root_url
      else
        @friendship = current_user.friendships.build(:friend_id => params[:friend_id])
        if @friendship.save
          flash[:notice] = "Added friend."
          redirect_to root_url
        else
          flash[:error] = "Unable to add friend."
          redirect_to root_url
        end
      end 
    end
    
    def destroy
      @friendship = current_user.friendships.find(params[:id])
      @friendship.destroy
      flash[:notice] = "Removed friendship."
      redirect_to current_user
    end

end 

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_user!, only: [:edit, :update, :destroy]
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.search(params[:search])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
    @posts = Post.find(params[:id])
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = current_user.posts.build(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end
  
  def vote
    value = params[:type] == "up" ? 1 : -1
    @post = Post.find(params[:id])
    @post.add_or_update_evaluation(:votes, value, current_user)
    redirect_to :back
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:title, :category, :body)
    end
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
    
    def new
        @search = Search.new
        @categories = Post.uniq.pluck(:category)
    end 
    
    def create
        @search = Search.create(search_params)
        redirect_to @search
    end 

    def show
        @search = Search.find(params[:id])
    end
    
    private
    
    def search_params
        params.require(:search).permit(:category, :Username)
    end
    
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
    @user_post = Post.where(user_id: params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/comments/_comment.html.erb
<div class="comment">
<div class="media mb-4">
  <img class="d-flex mr-3 rounded-circle" src="http://placehold.it/50x50" alt="">
    <div class="media-body">
      <h5 class="mt-0"><%= comment.Username %> - Submitted <%= time_ago_in_words(comment.created_at) %> ago</h5>
        <%= comment.body %> 
    </div>
  </div>
  </div>
  <hr>
    <%= form_for [comment, Comment.new] do |f| %>
      <%= f.text_area :body, placeholder: "Add a Reply", :class => "form-control" %><br/>
      <%= f.submit "Reply", :class => "btn btn-primary btn-sm" %>
      
      <!-- CHECK TO SEE IF USER SIGNED IN FOR EDIT AND DELETE-->
      <% if user_signed_in? && comment.user_id == current_user.id %>
      <%= link_to "Delete", [@post, comment], method: :delete, :class => "btn btn-primary btn-sm" %>
      <%= link_to "Edit", edit_post_comment_path(@post, comment), :class => "btn btn-primary btn-sm", :style => "color: white" %>
      <% end %>
      <!-- CHECK TO SEE IF USER SIGNED IN FOR EDIT AND DELETE-->
      
    <% end %>
  <ul>
    <%= render partial: 'comments/comment', collection: comment.comments %>
  </ul>

app/views/comments/edit.html.erb
<%= form_for (@comment) do |f| %>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>

 <%= f.submit "Reply", :class => "btn btn-primary btn-sm" %>

<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">Project Finder</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="http://projectfinder-mileswinston23.c9users.io">Home <span class="sr-only">(current)</span></a>
      </li>
      
      <% if !user_signed_in? %>
      
      <li class="nav-item">
        <a><%= link_to "Sign In", "http://projectfinder-mileswinston23.c9users.io/users/sign_in", :class => "nav-link" %></a>
      </li>
      
      <% else %>
      
      <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          My Account
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="https://projectfinder-mileswinston23.c9users.io/users/<%= current_user.id %>">My Profile</a>
          <a><%= link_to 'Create Post', new_post_path, :class => "dropdown-item" %></a>
          <a class="dropdown-item" href="https://projectfinder-mileswinston23.c9users.io/users/edit">Settings</a>
          <div class="dropdown-divider"></div>
          <a><%= link_to "Sign out", destroy_user_session_path, :method => :delete, :class => "dropdown-item" %></a>
        </div>
      </li>
      <% end %>
      
      <% if user_signed_in? %>
      
      <li class="nav-item">
        <a class="nav-link disabled" style="color: green;">Online: <%= current_user.Username %></a>
      </li>
      
      <% end %>
      
    </ul>
    
    
    
    <!--SEARCH-->
    <%= link_to "Advanced Search", new_search_path, :class => "nav-link" %>
    <%= form_tag posts_path, :method => 'get' do %>
      <%= text_field_tag :search, params[:search] %>
      <%= submit_tag "Search" %>
    <% end %>
    <!--SEARCH-->
  </div>
</nav>  
  

app/views/layouts/_sidenav.html.erb
  <!--<div class="rightcolumn">
    <div class="card">
      <h2>About Me</h2>
      <div class="fakeimg" style="height:100px;">Image</div>
      <p>Some text about me in culpa qui officia deserunt mollit anim..</p>
    </div>
    <div class="card">
      <h3>Popular Post</h3>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div><br>
      <div class="fakeimg">Image</div>
    </div>
    <div class="card">
      <h3>Follow Me</h3>
      <p>Some text..</p>
    </div>
  </div>
</div>
-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<%= render "layouts/header" %>
<%= render "layouts/sidenav" %>

<%= yield %>



</body>
</html>

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :category %><br>
    <%= f.select :category, options_for_select(["Home Renovation", "Outdoors", "Data Science", "Software Development", "Software Testing", "Graphic Design"]) %>
  </div>
  <div class="field">
    <%= f.label :body %><br>
    <%= f.text_area :body %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h1>Editing Post</h1>

<%= render 'form' %>

<%= link_to 'Show', @post %> |
<%= link_to 'Back', posts_path %>

app/views/posts/index.html.erb
<p id="notice"><%= notice %></p>

<div class="container">
<div class="index">
<h1>Listing Posts</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Category</th>
      <th>Created</th>
      <th>User</th>
      <th>rating</th>
      <th colspan="3"></th>
    </tr>

  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= link_to post.title, post %></td>
        <td><%= post.category %></td>
        <td><%= post.created_at.strftime("%A, %d %b %Y %l:%M %p") %></td>
        <td><%= link_to post.user.Username, user_path(post.user.id) %></td>
        <td>
          <em><%= pluralize post.reputation_for(:votes).to_i, "vote" %>
            <span><%= link_to "| up |", vote_post_path(post, type: "up"), method: "post" %></span>
            <span><%= link_to " down|", vote_post_path(post, type: "down"), method: "post" %></span>
          </em>
        </td>
        
        <% if user_signed_in? && post.user_id == current_user.id %>
        
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>
<br>

</div>
</div>

app/views/posts/new.html.erb
<h1>New Post</h1>

<%= render 'form' %>

<%= link_to 'Back', posts_path %>

app/views/posts/show.html.erb
<div class="row" id="post-comments">
<div class="col-lg-8">
<p id="notice"><%= notice %></p>

<!-- POST INFORMATION -->
<h1 class="mt-4"><%= @post.title %></h1>
<!--TITLE-->
<p class="lead">by <%= link_to @post.user.Username, user_path(@post.user.id) %>
</p>
<!--IMAGE-->
<img class="img-fluid rounded" src="http://placehold.it/900x300" alt="">
<hr>
<!--BODY-->
<p>
<%= simple_format(@post.body) %>
</p>
<hr>
<!--POSTED AT-->
<p><strong>Posted at:</strong>
<%= time_ago_in_words(@post.created_at) %></p>
<hr>
<!--CATEGORY-->
<p>
  <strong>Category:</strong>
  <%= @post.category %>
</p>
<!-- POST INFORMATION -->

<!-- IF USER IS SIGNED IN, LET USER EDIT POST -->
<% if user_signed_in? && @post.user_id == current_user.id %>
<%= link_to 'Edit', edit_post_path(@post) %> |
<% end %>
<!-- IF USER IS SIGNED IN, LET USER EDIT POST -->

<%= link_to 'Back', posts_path %>

<!-- LEAVE A COMMENT BOX -->
<div class="reply">
 <h5 class="card-header">Leave a Comment:</h5><%= form_for [@post, Comment.new] do |f| %>
  <div class="card-body">
    <form>
      <div class="form-group">
      <%= f.text_area :body, placeholder: "Add a comment", :class => "form-control", :rows => "3" %><br />
      </div>
      <%= f.submit "Add Comment", :class => "btn btn-primary" %>
      <% end %>
    </form>
  </div>
  </div>
<%= render(partial: 'comments/comment', collection: @post.comments) %>
<!-- LEAVE A COMMENT BOX -->

</div>
</div>

app/views/searches/new.html.erb
<h1>Advanced Search</h1>

<%= form_for @search, html: {class: "pure-form"} do |f| %>

    <div class="field">
        <%= f.label :category %><br />
        <%= f.select :category, options_for_select(@categories) %> 
    </div>

    <div class="actions"><%= f.submit "Search", class: "pure-button pure-button-primary" %></div>
    
    <% end %>
    
    <p><%= link_to "Back", posts_path %></p>

app/views/searches/show.html.erb
<h1>Search Results</h1>

<p><%= link_to 'Back', new_search_path %></p>

<% if @search.search_posts.empty? %>

    <p>No Records Found</p>

<% else %>

    <% @search.search_posts.each do |s| %>
        <br>
        
        <div class="div">
            <h1>Title: <%= s.title %></h1>
            <p>Category: <%= s.category %></p>
            <p>Body: <%= s.body %></p>
        </div>
    <% end %>
<% end %>

app/views/users/index.html.erb
<div class="container" style="margin-top: 10%">
<% @users.each do |user| %>
<br>
<%= link_to user.username, user %>
<%= user.email %>
<% end %>
</div>

app/views/users/show.html.erb
<div class="container">
    <div class="profile">
        <div class="row">
          
            <!-- FRIENDS -->
            <div class="column-md-4" id="followers">
                <div class="card" style="width: 18rem;">
                <div class="card-body">
                <div class="card-title">Friends</div>
                  <ul class="list-group list-group-flush">
                  <% for friendship in @user.friendships %>
                    <li class="list-item">
                      <%=h link_to friendship.friend.Username, user_path(friendship.friend_id) %>
                      
                      <% if user_signed_in? && @user.id == current_user.id %>
                      
                      (<%= link_to "remove", friendship, :method => :delete %>)
                      
                      <% end %>
                    </li>
                  <% end %>
                </ul>
                <!-- FRIENDS -->
                <!-- FRIENDED BY -->
                <br>
                <div class="card-title">Friended by Users</div>
                <ul class="list-group list-group-flush">
                  <% for user in @user.inverse_friends %>
                    <li class="list-item">
                      <%=h link_to user.Username,  user_path(user.id) %>
                    </li>
                  <% end %>
                </ul>
                <!-- FRIENDED BY -->
            </div>
            </div>
            </div>
            
            <!--PROFILE-->
            <div class="column-md-4" id="profile">
            <div class="card" id="profile-card">
                <% if @user.image.file? %>
                  <%= image_tag @user.image.url, :class => "img-fluid" %>
                <% else %>
                  <%= image_tag 'placehold.gif', :class => "img-fluid"  %>
                <% end %>
                <div class="card-body">
                <h5 class="card-title"><%= @user.Username %></h5>
                <p class="card-text"><%= @user.Biography %></p>
                </div>
                <ul class="list-group list-group-flush">
                <li class="list-group-item">Email: <%= mail_to @user.email %></li>
                <li class="list-group-item">Education: <%= @user.Education %></li>
                <li class="list-group-item">Profession: <%= @user.Profession %></li>
                <li class="list-group-item">Location: <%= @user.Location %></li>
                
                 <% if user_signed_in? && @user.id != current_user.id %>
 
                <li class="list-group-item"><%= link_to "Add Friend", friendships_path(:friend_id => @user), :method => :post %></li>
                
                <% end %>
                
                </ul>
                </div>
            </div>
            <!--PROFILE-->
            
            <!--RECENTLY POSTED-->
            <div class="column-md-4" id="recent-user-posts">
            <div class="card" style="width: 18rem;">
            <div class="card-title">
                Recently Posted
            </div>
            <ul class="list-group list-group-flush">
            <% @user_post.each do |post| %> 
                    <li class="list-group-item"><%= link_to post.title, post_path(post.id) %>
                    <%= time_ago_in_words(post.created_at) %> ago
     
                    <% if user_signed_in? && post.user_id == current_user.id %>
                    <br>
                    <%= link_to 'Edit', edit_post_path(post) %>
                    <%= link_to 'Delete', post, method: :delete, data: { confirm: 'Are you sure?' } %>    
                    
                    <% end %>
                    </li>
                    <% end %>
                  </ul>
                </div>
            </div>
            <!--RECENTLY POSTED-->

        </div>
    </div>
</div>